-- Migration 001: Create platform_secrets table
-- Service: defi
-- Purpose: Stores platform-level API keys and secrets managed by administrators
--          through the admin API. Values are stored as text; AES-256-GCM
--          encryption via KMS must be applied before this table goes to
--          production (the column name value_enc signals that expectation).

CREATE TABLE IF NOT EXISTS platform_secrets (
    id           UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    key_name     VARCHAR(100)                NOT NULL UNIQUE,
    value_enc    TEXT                        NOT NULL,
    description  VARCHAR(500),
    updated_by   VARCHAR(200)                NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_platform_secrets_key_name ON platform_secrets (key_name);

COMMENT ON TABLE  platform_secrets              IS 'Platform-level API keys and secrets configurable by administrators at runtime.';
COMMENT ON COLUMN platform_secrets.id           IS 'UUID v4 generated by the database via gen_random_uuid().';
COMMENT ON COLUMN platform_secrets.key_name     IS 'Logical name matching the DEFI_<KEY_NAME> environment variable convention (e.g. coingecko_api_key).';
COMMENT ON COLUMN platform_secrets.value_enc    IS 'Secret value. Must be AES-256-GCM encrypted via KMS before production — currently stored as plain text for development only.';
COMMENT ON COLUMN platform_secrets.description  IS 'Optional human-readable note about the purpose of this secret.';
COMMENT ON COLUMN platform_secrets.updated_by   IS 'Identifier (e-mail or UUID) of the administrator who last modified this record.';
