-- Migration 001: Create auth_tokens table
-- Service: auth
-- Purpose: Stores M2M JWT tokens issued for machine-to-machine authentication

CREATE TABLE IF NOT EXISTS public.auth_tokens (
    id          UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id   VARCHAR(64)                 NOT NULL,
    jwt_token   TEXT                        NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    expires_at  TIMESTAMP WITH TIME ZONE    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_auth_tokens_client_id ON public.auth_tokens (client_id);
CREATE INDEX IF NOT EXISTS idx_auth_tokens_expires_at ON public.auth_tokens (expires_at);

COMMENT ON TABLE  public.auth_tokens          IS 'M2M JWT tokens for machine-to-machine authentication.';
COMMENT ON COLUMN public.auth_tokens.id       IS 'UUID v4 generated by the database via gen_random_uuid().';
COMMENT ON COLUMN public.auth_tokens.client_id IS 'Client identifier that requested the token.';
COMMENT ON COLUMN public.auth_tokens.jwt_token IS 'Signed JWT token using Ed25519 algorithm.';
COMMENT ON COLUMN public.auth_tokens.created_at IS 'Timestamp when the token was created.';
COMMENT ON COLUMN public.auth_tokens.expires_at IS 'Timestamp when the token expires (TTL = 120s).';
