-- Migration 001: Create btc_nodes table
-- Service: blockchain/bitcoin
-- Purpose: Persists node configuration, last-seen block height, and status
--          for health monitoring and observability.
-- Note: gen_random_uuid() is built-in since PostgreSQL 13. For older
--       versions enable pgcrypto first: CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS btc_nodes (
    id               UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    name             VARCHAR(100)                NOT NULL UNIQUE,
    url              VARCHAR(500)                NOT NULL,
    priority         INTEGER                     NOT NULL DEFAULT 1,
    status           VARCHAR(20)                 NOT NULL DEFAULT 'unknown',
    last_seen_block  BIGINT,
    last_checked_at  TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_btc_nodes_status   ON btc_nodes (status);
CREATE INDEX IF NOT EXISTS idx_btc_nodes_priority ON btc_nodes (priority ASC);

COMMENT ON TABLE  btc_nodes                 IS 'Bitcoin Core node registry with live health state.';
COMMENT ON COLUMN btc_nodes.id              IS 'UUID v4 generated by the database via gen_random_uuid().';
COMMENT ON COLUMN btc_nodes.priority        IS 'Lower value = higher priority for failover ordering.';
COMMENT ON COLUMN btc_nodes.status          IS 'healthy | degraded | down | unknown';
COMMENT ON COLUMN btc_nodes.last_seen_block IS 'Most recent block height successfully fetched from this node.';
