"""GET /v1/defi/indexes must authenticate via the REQUIRED ``authorization``
query parameter using the token generated by ``POST /auth/token`` — consistent
with every endpoint served through ``get_current_token`` (except ``POST
/auth/token`` and ``/auth/token/validate``).
"""

from __future__ import annotations

from unittest.mock import patch

import jwt
import pytest
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
from fastapi import FastAPI
from fastapi.testclient import TestClient

from app.services.defi.api.routers.defi_router import router


def _keypair() -> tuple[str, str]:
    private_key = Ed25519PrivateKey.generate()
    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    ).decode()
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    ).decode()
    return private_pem, public_pem


PRIVATE_KEY, PUBLIC_KEY = _keypair()


class _FakeIndexService:
    async def list_indices(self) -> list:
        return []


@pytest.fixture
def client() -> TestClient:
    app = FastAPI()
    app.state.index_service = _FakeIndexService()
    app.include_router(router)
    return TestClient(app)


def _token(**claims) -> str:
    payload = {"sub": "client123", "iss": "auth_service", "type": "m2m"}
    payload.update(claims)
    return jwt.encode(payload, PRIVATE_KEY, algorithm="EdDSA")


class TestIndexesQueryAuthorization:
    """FEATURE: ''authorization'' query parameter on GET /v1/defi/indexes."""

    def test_get_indexes_with_authorization_query_param_returns_200(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get("/v1/defi/indexes", params={"authorization": _token()})
        assert resp.status_code == 200

    def test_get_indexes_with_bearer_query_param_returns_200(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get(
                "/v1/defi/indexes",
                params={"authorization": f"Bearer {_token()}"},
            )
        assert resp.status_code == 200

    def test_header_only_returns_422(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get(
                "/v1/defi/indexes",
                headers={"Authorization": f"Bearer {_token()}"},
            )
        assert resp.status_code == 422

    def test_missing_query_param_returns_422(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get("/v1/defi/indexes")
        assert resp.status_code == 422

    def test_empty_query_param_returns_401(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get("/v1/defi/indexes", params={"authorization": ""})
        assert resp.status_code == 401

    def test_invalid_token_query_param_returns_401(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get(
                "/v1/defi/indexes",
                params={"authorization": "not-a-valid-token"},
            )
        assert resp.status_code == 401

    def test_expired_token_query_param_returns_401(self, client):
        with patch("app.services.auth.api.dependencies._public_key", PUBLIC_KEY):
            resp = client.get(
                "/v1/defi/indexes",
                params={"authorization": _token(exp=0)},
            )
        assert resp.status_code == 401