-- Migration 001: Create eth_providers table
-- Service: blockchain/ethereum
-- Purpose: Persists provider configuration, last-seen block, and status
--          for health monitoring and observability.
-- Note: gen_random_uuid() is built-in since PostgreSQL 13. For older
--       versions enable pgcrypto first: CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS eth_providers (
    id               UUID                        PRIMARY KEY DEFAULT gen_random_uuid(),
    name             VARCHAR(100)                NOT NULL UNIQUE,
    url              VARCHAR(500)                NOT NULL,
    priority         INTEGER                     NOT NULL DEFAULT 1,
    status           VARCHAR(20)                 NOT NULL DEFAULT 'unknown',
    last_seen_block  BIGINT,
    last_checked_at  TIMESTAMP WITH TIME ZONE,
    created_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_eth_providers_status   ON eth_providers (status);
CREATE INDEX IF NOT EXISTS idx_eth_providers_priority ON eth_providers (priority ASC);

COMMENT ON TABLE  eth_providers                 IS 'Ethereum RPC provider registry with live health state.';
COMMENT ON COLUMN eth_providers.id              IS 'UUID v4 generated by the database via gen_random_uuid().';
COMMENT ON COLUMN eth_providers.priority        IS 'Lower value = higher priority for failover ordering.';
COMMENT ON COLUMN eth_providers.status          IS 'healthy | degraded | down | unknown';
COMMENT ON COLUMN eth_providers.last_seen_block IS 'Most recent block number successfully fetched from this provider.';
